import Head from 'next/head'
import tw from "tailwind-styled-components"
import Prueba from '../components/Prueba';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container $color={false}>
        <h1 className='text-6xl text-white'>Home Page</h1>
      </Container>

      <Prueba/>

    </div>
  )
};

const Container = tw.div`
    ${(prop) => prop.$color ? 'bg-red-500' : 'bg-blue-500'}
    flex
    items-center
    justify-center
    flex-col
    w-full
    text-black
`;


